**1) Data Types & Missing Values**

In [ ]:
# Import required libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
# Load dataset directly from GitHub

url = "https://raw.githubusercontent.com/vyasanbmathew2008/Team-6/main/healthcare-disease-prediction/dataset/healthcare_dataset.csv"

df = pd.read_csv(url)

print("Dataset loaded successfully.")
print(f"Dataset shape: {df.shape}")

Dataset loaded successfully.
Dataset shape: (55500, 15)

In [ ]:
# Display basic dataset information

print("Dataset Shape:", df.shape)

Dataset Shape: (55500, 15)

In [ ]:
# Display first 5 records

df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

In [ ]:
# Display last 5 records

df.tail()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
55495,eLIZABeTH jaCkSOn,42,Female,O+,Asthma,2020-08-16,Joshua Jarvis,Jones-Thompson,Blue Cross,2650.714952,417,Elective,2020-09-15,Penicillin,Abnormal
55496,KYle pEREz,61,Female,AB-,Obesity,2020-01-23,Taylor Sullivan,Tucker-Moyer,Cigna,31457.797307,316,Elective,2020-02-01,Aspirin,Normal
55497,HEATher WaNG,38,Female,B+,Hypertension,2020-07-13,Joe Jacobs DVM,"and Mahoney Johnson Vasquez,",UnitedHealthcare,27620.764717,347,Urgent,2020-08-10,Ibuprofen,Abnormal
55498,JENniFER JOneS,43,Male,O-,Arthritis,2019-05-25,Kimberly Curry,"Jackson Todd and Castro,",Medicare,32451.092358,321,Elective,2019-05-31,Ibuprofen,Abnormal
55499,jAMES GARCiA,53,Female,O+,Arthritis,2024-04-02,Dennis Warren,Henry Sons and,Aetna,4010.134172,448,Urgent,2024-04-29,Ibuprofen,Abnormal

In [ ]:
# Get number of rows and columns

rows, columns = df.shape

print(f"Number of rows    : {rows}")
print(f"Number of columns : {columns}")

Number of rows    : 55500
Number of columns : 15

In [ ]:
# Display all column names

print("Columns in the dataset:\n")

for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

Columns in the dataset:

1. Name
2. Age
3. Gender
4. Blood Type
5. Medical Condition
6. Date of Admission
7. Doctor
8. Hospital
9. Insurance Provider
10. Billing Amount
11. Room Number
12. Admission Type
13. Discharge Date
14. Medication
15. Test Results

In [ ]:
# Display dataset information

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 55500 entries, 0 to 55499
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Name                55500 non-null  object
 1   Age                 55500 non-null  int64
 2   Gender              55500 non-null  object
 3   Blood Type          55500 non-null  object
 4   Medical Condition   55500 non-null  object
 5   Date of Admission   55500 non-null  object
 6   Doctor              55500 non-null  object
 7   Hospital            55500 non-null  object
 8   Insurance Provider  55500 non-null  object
 9   Billing Amount      55500 non-null  float64
 10  Room Number         55500 non-null  int64
 11  Admission Type      55500 non-null  object
 12  Discharge Date      55500 non-null  object
 13  Medication          55500 non-null  object
 14  Test Results        55500 non-null  object
dtypes: float64(1), int64(2), object(12)
memory usage: 6.4+ MB

In [ ]:
# Display data type of every column

dtype_df = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str).values
})

dtype_df

                Column Data Type
0                 Name    object
1                  Age     int64
2               Gender    object
3           Blood Type    object
4    Medical Condition    object
5    Date of Admission    object
6               Doctor    object
7             Hospital    object
8   Insurance Provider    object
9       Billing Amount   float64
10         Room Number     int64
11      Admission Type    object
12      Discharge Date    object
13          Medication    object
14        Test Results    object

In [ ]:
# Count columns by data type

print("Number of columns by data type:\n")

print(df.dtypes.value_counts())

Number of columns by data type:

object     12
int64       2
float64     1
Name: count, dtype: int64

In [ ]:
# Identify numerical columns

numerical_columns = df.select_dtypes(include=np.number).columns.tolist()

print("Numerical Columns:\n")

for column in numerical_columns:
    print("-", column)

print(f"\nTotal numerical columns: {len(numerical_columns)}")

Numerical Columns:

- Age
- Billing Amount
- Room Number

Total numerical columns: 3

##Categorical/Text Columns

Categorical or text columns contain labels, categories, names, or other textual information.

These columns may require encoding before being used by machine learning algorithms.

In [ ]:
# Identify categorical/text columns

categorical_columns = df.select_dtypes(include="object").columns.tolist()

print("Categorical/Text Columns:\n")

for column in categorical_columns:
    print("-", column)

print(f"\nTotal categorical/text columns: {len(categorical_columns)}")

Categorical/Text Columns:

- Name
- Gender
- Blood Type
- Medical Condition
- Date of Admission
- Doctor
- Hospital
- Insurance Provider
- Admission Type
- Discharge Date
- Medication
- Test Results

Total categorical/text columns: 12

In [ ]:
# Identify columns containing "date" in their name

date_columns = [
    column for column in df.columns
    if "date" in column.lower()
]

print("Potential Date Columns:\n")

for column in date_columns:
    print("-", column)

Potential Date Columns:

- Date of Admission
- Discharge Date

In [ ]:
# Display data types of date-related columns

print("Date Column Data Types:\n")

for column in date_columns:
    print(f"{column}: {df[column].dtype}")

Date Column Data Types:

Date of Admission: object
Discharge Date: object

##Unique Values

In [ ]:
# Count unique values in each column

unique_values_df = pd.DataFrame({
    "Column": df.columns,
    "Unique Values": [
        df[column].nunique(dropna=True)
        for column in df.columns
    ]
})

unique_values_df

                Column  Unique Values
0                 Name          49992
1                  Age             77
2               Gender              2
3           Blood Type              8
4    Medical Condition              6
5    Date of Admission           1827
6               Doctor          40341
7             Hospital          39876
8   Insurance Provider              5
9       Billing Amount          50000
10         Room Number            400
11      Admission Type              3
12      Discharge Date           1856
13          Medication              5
14        Test Results              3

In [ ]:
# Create complete column summary

column_summary = pd.DataFrame({
    "Column": df.columns,
    "Data Type": df.dtypes.astype(str).values,
    "Non-Null Count": df.notnull().sum().values,
    "Missing Count": df.isnull().sum().values,
    "Unique Values": df.nunique(dropna=True).values
})

column_summary

                Column Data Type  Non-Null Count  Missing Count  Unique Values
0                 Name    object           55500              0          49992
1                  Age     int64           55500              0             77
2               Gender    object           55500              0              2
3           Blood Type    object           55500              0              8
4    Medical Condition    object           55500              0              6
5    Date of Admission    object           55500              0           1827
6               Doctor    object           55500              0          40341
7             Hospital    object           55500              0          39876
8   Insurance Provider    object           55500              0              5
9       Billing Amount   float64           55500              0          50000
10         Room Number     int64           55500              0            400
11      Admission Type    object           55500              0              3
12      Discharge Date    object           55500              0           1856
13          Medication    object           55500              0              5
14        Test Results    object           55500              0              3

# Missing Value Analysis

Missing values can affect data analysis and machine learning models.

We will check:

1. Missing values in each column
2. Missing-value percentage
3. Columns containing missing values
4. Total missing values in the dataset

In [ ]:
# Count missing values in each column

missing_count = df.isnull().sum()

print("Missing values in each column:\n")

print(missing_count)

Missing values in each column:

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [ ]:
# Calculate missing-value percentage

missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_df = pd.DataFrame({
    "Column": df.columns,
    "Missing Values": df.isnull().sum().values,
    "Missing Percentage": missing_percentage.values
})

missing_df = missing_df.sort_values(
    by="Missing Values",
    ascending=False
)

missing_df

                Column  Missing Values  Missing Percentage
0                 Name               0                 0.0
1                  Age               0                 0.0
2               Gender               0                 0.0
3           Blood Type               0                 0.0
4    Medical Condition               0                 0.0
5    Date of Admission               0                 0.0
6               Doctor               0                 0.0
7             Hospital               0                 0.0
8   Insurance Provider               0                 0.0
9       Billing Amount               0                 0.0
10         Room Number               0                 0.0
11      Admission Type               0                 0.0
12      Discharge Date               0                 0.0
13          Medication               0                 0.0
14        Test Results               0                 0.0

In [ ]:
# Display only columns containing missing values

missing_only = missing_df[
    missing_df["Missing Values"] > 0
]

if len(missing_only) > 0:
    display(missing_only)
else:
    print("No columns contain missing values.")

No columns contain missing values.

In [ ]:
# Calculate overall percentage of missing cells

total_cells = df.shape[0] * df.shape[1]

overall_missing_percentage = (
    total_missing / total_cells
) * 100

print(
    f"Overall percentage of missing cells: "
    f"{overall_missing_percentage:.2f}%"
)

Overall percentage of missing cells: 0.00%

#Dataset Summary

In [ ]:
# Generate automatic summary values for documentation

print("DATASET SUMMARY")
print("=" * 50)

print(f"Number of records       : {df.shape[0]}")
print(f"Number of columns       : {df.shape[1]}")
print(f"Numerical columns       : {len(numerical_columns)}")
print(f"Categorical/Text columns: {len(categorical_columns)}")
print(f"Date-related columns   : {len(date_columns)}")
print(f"Total missing values    : {total_missing}")
print(
    f"Missing cell percentage : "
    f"{overall_missing_percentage:.2f}%"
)

if total_missing > 0:
    highest_missing_column = missing_df.iloc[0]["Column"]
    highest_missing_count = missing_df.iloc[0]["Missing Values"]

    print(
        f"Highest missing column  : "
        f"{highest_missing_column} "
        f"({highest_missing_count} values)"
    )
else:
    print("Highest missing column  : None")

DATASET SUMMARY
==================================================
Number of records       : 55500
Number of columns       : 15
Numerical columns       : 3
Categorical/Text columns: 12
Date-related columns   : 2
Total missing values    : 0
Missing cell percentage : 0.00%
Highest missing column  : None